dataio:
  srcdir_dataset: /local/datasets/real

  # obj_sdf_shape: disc
  # obj_sdf_shape: rect
  obj_sdf_shape: ellip

  # 0: disc, 1: rect-edges, 2: rect-corners, 3: ellip
  class_label: 3

  num_classes: 4

  num_steps: 450
  num_seqs: 50
  num_eps_seq: 3

  # disc datasets [*-straight-line-*,  *-curves-*, *-trial1-*]
  # dataset_name: 20200624_pushing-6in-disc-curves-test-keypoint
  # dataset_name: 20200624_pushing-6in-disc-trial1-all-keypoint

  # rect datasets [*-edges-*, *-corners-*]
  # dataset_name: 20200928_rectangle-pushing-edges-test-keypoint
  # dataset_name: 20200928_rectangle-pushing-corners-test-keypoint

  # ellipse datasets [*-straight-*, *-*]
  # dataset_name: 20200928_ellipse-pushing-test-keypoint
  dataset_name: 20200928_ellipse-pushing-straight-test-keypoint

  # linear [disc+rect, auto-keypoints]
  # torch_model_name: 10-19-2020-14-18-53_tf_regr_model_ser_epoch030

  # linear [disc+rect+ellip, auto-keypoints]
  torch_model_name: 10-25-2020-16-40-01_tf_regr_model_ser_epoch030
  # torch_model_name: 10-25-2020-18-08-11_tf_regr_model_ser_epoch030

options:
  vis_step_flag: False
  random_seed: 0 

data_process:
  norm_img_feat: True
  mean_img_feat: [0.2002, 0.6032]
  std_img_feat: [0.0367, 0.1235]

noise_models:
  # std values
  obj_pose_prior: [1e-2, 1e-2, 1e-2]
  odom_motion: [1e-3, 1e-3, 1e-3]

  first_pose_prior: [1e-5, 1e-5, 1e-5]
  ee_pose_prior: [1e-5, 1e-5, 1e-5]
  obj_pose_interseq_noise: [1e-9, 1e-9, 1e-9]

  qs_push_motion: [1e-3, 1e-3, 1e-3]
  sdf_intersection: [1e-2]
  tactile_rel_meas: [1, 1, 1e-5]

factors:
  enable_qs_motion: True
  enable_sdf_intersection: True
  enable_tactile_rel_meas: True

  # tactile factor flags
  yaw_only_error: True
  constant_model: False
  tactile_oracle: False

  # prefix: qs+sdf
  prefix: qs+sdf+tactile-linear
  # prefix: qs+sdf+tactile-const
  # prefix: qs+sdf+tactile-oracle

  # range of pose pairs for tactile_rel factors
  tactile_min_offset: 10
  tactile_max_offset: 40

  obj_prior_interval: 1e4
