dataset_names: [20200928_rectangle-pushing-corners-test-keypoint, 20200928_rectangle-pushing-edges-test-keypoint]
# dataset_names: [20200624_pushing-6in-disc-trial1-all-keypoint, 20200624_pushing-6in-disc-curves-test-keypoint]
# dataset_names: [20200928_ellipse-pushing-test-keypoint, 20200928_ellipse-pushing-straight-test-keypoint]

obj_sdf_shape: rect
# obj_sdf_shape: disc
# obj_sdf_shape: ellip

options:
  random_seed: 0

logger:
  names:
    [
      "qs+sdf",
      "qs+sdf+tactile-const",
      "qs+sdf+tactile-linear",
      "qs+sdf+tactile-oracle",
    ]
  labels:
    [
      "no tactile", 
      "const tactile", 
      "learnt tactile (ours)", 
      "oracle tactile"
    ]
  colors: 
    [
      [0, 0.4470, 0.7410], 
      [0.4940, 0.1840, 0.5560], 
      [0.8500, 0.3250, 0.0980], 
      [0.4660, 0.6740, 0.1880]
    ]

  fields:
    poses_ee_gt: poses2d/ee_gt
    poses_ee_graph: poses2d/ee_graph

    poses_obj_gt: poses2d/obj_gt
    poses_obj_graph: poses2d/obj_graph

  num_seqs: [50, 50]
  # num_seqs: [33, 15]
  # num_seqs: [50, 17]

  num_steps: 450
  freq: 30

  start_seq_idx: 0

  dir_prefix: 'params003'